import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ReactScanProvider } from "@/components/ReactScanProvider";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<head>
				<meta name="apple-mobile-web-app-title" content="McOutline" />
			</head>
			<body>
				<ReactScanProvider>
					<TRPCReactProvider>{children}</TRPCReactProvider>
					<Toaster />
				</ReactScanProvider>
			</body>
		</html>
	);
}
